version: "3.5"

services: 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports: 
      - 5672:5672
      - 15672:15672
    networks:
      - dsn
    volumes:
      - rabbitmq:/var/lib/rabbitmq
networks: 
  dsn:
    name: dsn-network

volumes:
  rabbitmq:
    driver: local